Repository k2-fsa/sherpa-onnx, pull requests merged in 2025-10, with the labels that each got.

#2648 Reduce verbose output about reading lexicon for TTS
  sherpa-onnx/csrc/jieba-lexicon.cc
Labels: size:XS

#2651 Add more Piper TTS models
  .github/workflows/export-piper.yaml
  scripts/apk/generate-tts-apk-script.py
  scripts/piper/generate.py
  sherpa-onnx/csrc/jieba-lexicon.cc
Labels: size:M

#2652 Add CXX API for audio tagging
  .github/workflows/cxx-api.yaml
  cxx-api-examples/CMakeLists.txt
  cxx-api-examples/audio-tagging-ced-cxx-api.cc
  cxx-api-examples/audio-tagging-zipformer-cxx-api.cc
  sherpa-onnx/c-api/cxx-api.cc
  sherpa-onnx/c-api/cxx-api.h
Labels: size:L

#2656 Support https://github.com/ASLP-lab/WenetSpeech-Chuan
  .github/workflows/upload-models.yaml
  scripts/apk/generate-vad-asr-apk-script.py
  sherpa-onnx/kotlin-api/OfflineRecognizer.kt
Labels: size:M

#2657 Fix building for android
  .github/workflows/android.yaml
  cmake/onnxruntime.cmake
Labels: size:S

#2645 Fix ios build script
  build-ios.sh
  ios-swift/SherpaOnnx/SherpaOnnx.xcodeproj/project.pbxproj
  ios-swiftui/SherpaOnnx/SherpaOnnx.xcodeproj/project.pbxproj
  ios-swiftui/SherpaOnnx2Pass/SherpaOnnx2Pass.xcodeproj/project.pbxproj
  ios-swiftui/SherpaOnnxLangID/SherpaOnnxLangID.xcodeproj/project.pbxproj
  ios-swiftui/SherpaOnnxSubtitle/SherpaOnnxSubtitle.xcodeproj/project.pbxproj
Labels: size:S
