Repository k2-fsa/sherpa-onnx, pull requests merged in 2025-09, with the labels that each got.

#2545 Fix c api
  cmake/cppinyin.cmake
  cmake/cppinyin.patch
  scripts/dart/release.sh
  scripts/dotnet/OfflineRecognizerResult.cs
  scripts/dotnet/run.sh
  scripts/go/release.sh
  sherpa-onnx/c-api/c-api.h
  sherpa-onnx/c-api/cxx-api.cc
  sherpa-onnx/c-api/cxx-api.h
  sherpa-onnx/java-api/src/main/java/com/k2fsa/sherpa/onnx/OfflineRecognizer.java
  sherpa-onnx/java-api/src/main/java/com/k2fsa/sherpa/onnx/OfflineRecognizerResult.java
  sherpa-onnx/jni/offline-recognizer.cc
  sherpa-onnx/kotlin-api/OfflineRecognizer.kt
  swift-api-examples/SherpaOnnx.swift
Labels: size:L

#2547 Release 1.12.11
  CHANGELOG.md
  CMakeLists.txt
  android/SherpaOnnx/app/build.gradle
  android/SherpaOnnx2Pass/app/build.gradle
  android/SherpaOnnxAar/README.md
  android/SherpaOnnxAudioTagging/app/build.gradle.kts
  android/SherpaOnnxAudioTaggingWearOs/app/build.gradle.kts
  android/SherpaOnnxJavaDemo/app/build.gradle
  android/SherpaOnnxKws/app/build.gradle
  android/SherpaOnnxSimulateStreamingAsr/app/build.gradle.kts
  android/SherpaOnnxSimulateStreamingAsrWearOs/app/build.gradle.kts
  android/SherpaOnnxSpeakerDiarization/app/build.gradle.kts
  android/SherpaOnnxSpeakerIdentification/app/build.gradle.kts
  android/SherpaOnnxSpokenLanguageIdentification/app/build.gradle.kts
  android/SherpaOnnxTts/app/build.gradle
  android/SherpaOnnxTtsEngine/app/build.gradle.kts
  android/SherpaOnnxVad/app/build.gradle
  android/SherpaOnnxVadAsr/app/build.gradle
  android/SherpaOnnxWebSocket/app/build.gradle
  build-ios-shared.sh
  dart-api-examples/add-punctuations/pubspec.yaml
  dart-api-examples/audio-tagging/pubspec.yaml
  dart-api-examples/keyword-spotter/pubspec.yaml
  dart-api-examples/non-streaming-asr/pubspec.yaml
  dart-api-examples/speaker-diarization/pubspec.yaml
  dart-api-examples/speaker-identification/pubspec.yaml
  dart-api-examples/speech-enhancement-gtcrn/pubspec.yaml
  dart-api-examples/streaming-asr/pubspec.yaml
  dart-api-examples/tts/pubspec.yaml
  dart-api-examples/vad-with-non-streaming-asr/pubspec.yaml
  dart-api-examples/vad/pubspec.yaml
  flutter-examples/streaming_asr/pubspec.yaml
  flutter-examples/tts/pubspec.yaml
  flutter/sherpa_onnx/pubspec.yaml
  flutter/sherpa_onnx_ios/ios/sherpa_onnx_ios.podspec
  flutter/sherpa_onnx_macos/macos/sherpa_onnx_macos.podspec
  harmony-os/SherpaOnnxHar/sherpa_onnx/BuildProfile.ets
  harmony-os/SherpaOnnxHar/sherpa_onnx/README.md
  harmony-os/SherpaOnnxHar/sherpa_onnx/oh-package.json5
  harmony-os/SherpaOnnxSpeakerDiarization/entry/oh-package.json5
  harmony-os/SherpaOnnxSpeakerIdentification/entry/oh-package.json5
  harmony-os/SherpaOnnxStreamingAsr/entry/oh-package.json5
  harmony-os/SherpaOnnxTts/entry/oh-package.json5
  harmony-os/SherpaOnnxVadAsr/entry/README.md
  harmony-os/SherpaOnnxVadAsr/entry/oh-package.json5
  jitpack.yml
  mfc-examples/README.md
  new-release.sh
  nodejs-addon-examples/package.json
  nodejs-examples/package.json
  pom.xml
  scripts/wheel/sherpa-onnx-bin/setup.py
  scripts/wheel/sherpa-onnx-core/setup.py
  setup.py
  sherpa-onnx/csrc/offline-tts-zipvoice-frontend.cc
  sherpa-onnx/csrc/version.cc
Labels: size:M

#2550 Fix using sherpa-onnx as a cmake sub-project.
  .github/workflows/linux-jni.yaml
  cmake/cppinyin.cmake
Labels: size:XS

#2557 Disable loading libs from jar on Android.
  sherpa-onnx/java-api/src/main/java/com/k2fsa/sherpa/onnx/LibraryUtils.java
Labels: size:S

#2559 Avoid appending blanks for Cantonese vits tts.
  sherpa-onnx/csrc/lexicon.cc
Labels: size:XS

#2564 Add hint for loading model files from SD card on Android.
  sherpa-onnx/csrc/file-utils.cc
Labels: size:S

#2565 Update README to include https://github.com/Mentra-Community/MentraOS
  README.md
Labels: size:S

#2571 Export models from https://github.com/voicekit-team/T-one to sherpa-onnx
  .github/workflows/export-t-one-to-onnx.yaml
  .gitignore
  cmake/kaldi-native-fbank.cmake
  scripts/t-one/README.md
  scripts/t-one/add_meta_data.py
  scripts/t-one/generate_tokens.py
  scripts/t-one/run.sh
  scripts/t-one/test.py
Labels: size:L

#2575 Add C++ and Python support for T-one streaming Russian ASR models
  .github/scripts/test-python.sh
  .gitignore
  cxx-api-examples/punctuation-cxx-api.cc
  python-api-examples/online-t-one-ctc-decode-files.py
  scripts/t-one/test.py
  sherpa-onnx/csrc/CMakeLists.txt
  sherpa-onnx/csrc/cat.cc
  sherpa-onnx/csrc/cat.h
  sherpa-onnx/csrc/features.cc
  sherpa-onnx/csrc/features.h
  sherpa-onnx/csrc/jieba-lexicon.cc
  sherpa-onnx/csrc/offline-stream.h
  sherpa-onnx/csrc/offline-tts-zipvoice-impl.h
  sherpa-onnx/csrc/offline-tts-zipvoice-model.cc
  sherpa-onnx/csrc/offline-tts.cc
  sherpa-onnx/csrc/online-ctc-greedy-search-decoder.cc
  sherpa-onnx/csrc/online-ctc-model.cc
  sherpa-onnx/csrc/online-model-config.cc
  sherpa-onnx/csrc/online-model-config.h
  sherpa-onnx/csrc/online-recognizer-ctc-impl.h
  sherpa-onnx/csrc/online-recognizer-impl.cc
  sherpa-onnx/csrc/online-t-one-ctc-model-config.cc
  sherpa-onnx/csrc/online-t-one-ctc-model-config.h
  sherpa-onnx/csrc/online-t-one-ctc-model.cc
  sherpa-onnx/csrc/online-t-one-ctc-model.h
  sherpa-onnx/csrc/onnx-utils.cc
  sherpa-onnx/csrc/onnx-utils.h
  sherpa-onnx/csrc/sherpa-onnx.cc
  sherpa-onnx/csrc/text-utils-test.cc
  sherpa-onnx/csrc/unbind.cc
  sherpa-onnx/csrc/unbind.h
  sherpa-onnx/python/csrc/CMakeLists.txt
  sherpa-onnx/python/csrc/offline-tts.cc
  sherpa-onnx/python/csrc/online-model-config.cc
  sherpa-onnx/python/csrc/online-t-one-ctc-model-config.cc
  sherpa-onnx/python/csrc/online-t-one-ctc-model-config.h
  sherpa-onnx/python/sherpa_onnx/online_recognizer.py
Labels: size:XL

#2577 Fix the missing online punctuation in android aar
  .github/workflows/android.yaml
  android/SherpaOnnxAar/sherpa_onnx/src/main/java/com/k2fsa/sherpa/onnx/OnlinePunctuation.kt
Labels: size:XS

#2580 Upload new sense-voice models
  .github/workflows/upload-models.yaml
  scripts/apk/generate-asr-2pass-apk-script.py
  scripts/apk/generate-vad-asr-apk-script.py
  sherpa-onnx/kotlin-api/OfflineRecognizer.kt
Labels: size:M

#2582 Export ASLP-lab/WSYue-ASR/tree/main/u2pp_conformer_yue to sherpa-onnx
  .github/workflows/upload-models.yaml
Labels: size:S

#2584 Add various languge bindings for Wenet non-streaming CTC models
  .github/scripts/test-dart.sh
  .github/scripts/test-dot-net.sh
  .github/scripts/test-nodejs-addon-npm.sh
  .github/scripts/test-nodejs-npm.sh
  .github/scripts/test-swift.sh
  .github/workflows/c-api.yaml
  .github/workflows/cxx-api.yaml
  .github/workflows/test-go.yaml
  .gitignore
  c-api-examples/CMakeLists.txt
  c-api-examples/wenet-ctc-c-api.c
  cxx-api-examples/CMakeLists.txt
  cxx-api-examples/wenet-ctc-cxx-api.cc
  cxx-api-examples/wenet-ctc-simulate-streaming-microphone-cxx-api.cc
  dart-api-examples/non-streaming-asr/bin/wenet-ctc.dart
  dart-api-examples/non-streaming-asr/run-wenet-ctc.sh
  dotnet-examples/offline-decode-files/Program.cs
  dotnet-examples/offline-decode-files/run-wenet-ctc.sh
  flutter/sherpa_onnx/lib/src/offline_recognizer.dart
  flutter/sherpa_onnx/lib/src/sherpa_onnx_bindings.dart
  go-api-examples/non-streaming-decode-files/main.go
  go-api-examples/non-streaming-decode-files/run-wenet-ctc.sh
  harmony-os/SherpaOnnxHar/sherpa_onnx/Index.ets
  harmony-os/SherpaOnnxHar/sherpa_onnx/src/main/cpp/non-streaming-asr.cc
  harmony-os/SherpaOnnxHar/sherpa_onnx/src/main/ets/components/NonStreamingAsr.ets
  java-api-examples/NonStreamingDecodeFileWenetCtc.java
  java-api-examples/run-non-streaming-decode-file-wenet-ctc.sh
  kotlin-api-examples/run.sh
  kotlin-api-examples/test_offline_wenet_ctc.kt
  nodejs-addon-examples/README.md
  nodejs-addon-examples/test_asr_non_streaming_wenet_ctc.js
  nodejs-examples/README.md
  nodejs-examples/test-offline-wenet-ctc.js
  pascal-api-examples/non-streaming-asr/.gitignore
  pascal-api-examples/non-streaming-asr/run-wenet-ctc.sh
  pascal-api-examples/non-streaming-asr/wenet_ctc.pas
  scripts/apk/generate-asr-2pass-apk-script.py
  scripts/apk/generate-vad-asr-apk-script.py
  scripts/dotnet/OfflineModelConfig.cs
  scripts/dotnet/OfflineWenetCtcModelConfig.cs
  scripts/go/_internal/non-streaming-decode-files/run-wenet-ctc.sh
  scripts/go/sherpa_onnx.go
  sherpa-onnx/c-api/c-api.cc
  sherpa-onnx/c-api/c-api.h
  sherpa-onnx/c-api/cxx-api.cc
  sherpa-onnx/c-api/cxx-api.h
  sherpa-onnx/java-api/Makefile
  sherpa-onnx/java-api/src/main/java/com/k2fsa/sherpa/onnx/OfflineModelConfig.java
  sherpa-onnx/java-api/src/main/java/com/k2fsa/sherpa/onnx/OfflineWenetCtcModelConfig.java
  sherpa-onnx/jni/offline-recognizer.cc
  sherpa-onnx/kotlin-api/OfflineRecognizer.kt
  sherpa-onnx/pascal-api/sherpa_onnx.pas
  swift-api-examples/.gitignore
  swift-api-examples/SherpaOnnx.swift
  swift-api-examples/run-wenet-ctc-asr.sh
  swift-api-examples/wenet-ctc-asr.swift
  wasm/asr/sherpa-onnx-asr.js
  wasm/nodejs/sherpa-onnx-wasm-nodejs.cc
Labels: size:XL

#2586 Release v1.12.12
  CHANGELOG.md
  CMakeLists.txt
  android/SherpaOnnx/app/build.gradle
  android/SherpaOnnx2Pass/app/build.gradle
  android/SherpaOnnxAar/README.md
  android/SherpaOnnxAudioTagging/app/build.gradle.kts
  android/SherpaOnnxAudioTaggingWearOs/app/build.gradle.kts
  android/SherpaOnnxJavaDemo/app/build.gradle
  android/SherpaOnnxKws/app/build.gradle
  android/SherpaOnnxSimulateStreamingAsr/app/build.gradle.kts
  android/SherpaOnnxSimulateStreamingAsrWearOs/app/build.gradle.kts
  android/SherpaOnnxSpeakerDiarization/app/build.gradle.kts
  android/SherpaOnnxSpeakerIdentification/app/build.gradle.kts
  android/SherpaOnnxSpokenLanguageIdentification/app/build.gradle.kts
  android/SherpaOnnxTts/app/build.gradle
  android/SherpaOnnxTtsEngine/app/build.gradle.kts
  android/SherpaOnnxVad/app/build.gradle
  android/SherpaOnnxVadAsr/app/build.gradle
  android/SherpaOnnxWebSocket/app/build.gradle
  build-ios-shared.sh
  dart-api-examples/add-punctuations/pubspec.yaml
  dart-api-examples/audio-tagging/pubspec.yaml
  dart-api-examples/keyword-spotter/pubspec.yaml
  dart-api-examples/non-streaming-asr/pubspec.yaml
  dart-api-examples/speaker-diarization/pubspec.yaml
  dart-api-examples/speaker-identification/pubspec.yaml
  dart-api-examples/speech-enhancement-gtcrn/pubspec.yaml
  dart-api-examples/streaming-asr/pubspec.yaml
  dart-api-examples/tts/pubspec.yaml
  dart-api-examples/vad-with-non-streaming-asr/pubspec.yaml
  dart-api-examples/vad/pubspec.yaml
  flutter-examples/streaming_asr/pubspec.yaml
  flutter-examples/tts/pubspec.yaml
  flutter/sherpa_onnx/pubspec.yaml
  flutter/sherpa_onnx_ios/ios/sherpa_onnx_ios.podspec
  flutter/sherpa_onnx_macos/macos/sherpa_onnx_macos.podspec
  harmony-os/SherpaOnnxHar/sherpa_onnx/BuildProfile.ets
  harmony-os/SherpaOnnxHar/sherpa_onnx/README.md
  harmony-os/SherpaOnnxHar/sherpa_onnx/oh-package.json5
  harmony-os/SherpaOnnxSpeakerDiarization/entry/oh-package.json5
  harmony-os/SherpaOnnxSpeakerIdentification/entry/oh-package.json5
  harmony-os/SherpaOnnxStreamingAsr/entry/oh-package.json5
  harmony-os/SherpaOnnxTts/entry/oh-package.json5
  harmony-os/SherpaOnnxVadAsr/entry/README.md
  harmony-os/SherpaOnnxVadAsr/entry/oh-package.json5
  jitpack.yml
  mfc-examples/README.md
  new-release.sh
  nodejs-addon-examples/package.json
  nodejs-examples/package.json
  pom.xml
  scripts/wheel/sherpa-onnx-bin/setup.py
  scripts/wheel/sherpa-onnx-core/setup.py
  setup.py
  sherpa-onnx/csrc/version.cc
Labels: size:M

#2596 Add Dart API for spoken language identification
  dart-api-examples/spoken-language-identification/README.md
  dart-api-examples/spoken-language-identification/analysis_options.yaml
  dart-api-examples/spoken-language-identification/bin/init.dart
  dart-api-examples/spoken-language-identification/bin/spoken_language_identification.dart
  dart-api-examples/spoken-language-identification/pubspec.yaml
  dart-api-examples/spoken-language-identification/run-whisper.sh
  flutter/sherpa_onnx/lib/sherpa_onnx.dart
  flutter/sherpa_onnx/lib/src/sherpa_onnx_bindings.dart
  flutter/sherpa_onnx/lib/src/spoken_language_identification.dart
Labels: size:L

#2599 Provide pre-compiled shepra-onnx libs/binaries for CUDA 12.x + onnxruntime 1.22.0
  .github/workflows/linux-gpu.yaml
  .github/workflows/windows-x64-cuda.yaml
  cmake/onnxruntime.cmake
  sherpa-onnx/csrc/CMakeLists.txt
Labels: size:L

#2607 Add a C++ example for simulated streaming ASR
  .github/workflows/aarch64-linux-gnu-shared.yaml
  .github/workflows/aarch64-linux-gnu-static.yaml
  .github/workflows/build-wheels-aarch64-cuda.yaml
  .github/workflows/build-wheels-aarch64-rknn.yaml
  .github/workflows/build-wheels-aarch64.yaml
  .github/workflows/build-wheels-linux-cuda.yaml
  .github/workflows/build-wheels-linux.yaml
  .github/workflows/linux-gpu.yaml
  .github/workflows/linux-jni-aarch64.yaml
  .github/workflows/linux-jni.yaml
  .github/workflows/linux.yaml
  .github/workflows/rknn-linux-aarch64.yaml
  CMakeLists.txt
  build-aarch64-linux-gnu.sh
  cmake/cmake_extension.py
  cmake/portaudio.cmake
  sherpa-onnx/csrc/CMakeLists.txt
  sherpa-onnx/csrc/sherpa-display.h
  sherpa-onnx/csrc/sherpa-onnx-vad-microphone-simulated-streaming-asr.cc
Labels: size:L

#2608 Release v1.12.14
  CHANGELOG.md
  CMakeLists.txt
  android/SherpaOnnx/app/build.gradle
  android/SherpaOnnx2Pass/app/build.gradle
  android/SherpaOnnxAar/README.md
  android/SherpaOnnxAudioTagging/app/build.gradle.kts
  android/SherpaOnnxAudioTaggingWearOs/app/build.gradle.kts
  android/SherpaOnnxJavaDemo/app/build.gradle
  android/SherpaOnnxKws/app/build.gradle
  android/SherpaOnnxSimulateStreamingAsr/app/build.gradle.kts
  android/SherpaOnnxSimulateStreamingAsrWearOs/app/build.gradle.kts
  android/SherpaOnnxSpeakerDiarization/app/build.gradle.kts
  android/SherpaOnnxSpeakerIdentification/app/build.gradle.kts
  android/SherpaOnnxSpokenLanguageIdentification/app/build.gradle.kts
  android/SherpaOnnxTts/app/build.gradle
  android/SherpaOnnxTtsEngine/app/build.gradle.kts
  android/SherpaOnnxVad/app/build.gradle
  android/SherpaOnnxVadAsr/app/build.gradle
  android/SherpaOnnxWebSocket/app/build.gradle
  build-ios-shared.sh
  dart-api-examples/add-punctuations/pubspec.yaml
  dart-api-examples/audio-tagging/pubspec.yaml
  dart-api-examples/keyword-spotter/pubspec.yaml
  dart-api-examples/non-streaming-asr/pubspec.yaml
  dart-api-examples/speaker-diarization/pubspec.yaml
  dart-api-examples/speaker-identification/pubspec.yaml
  dart-api-examples/speech-enhancement-gtcrn/pubspec.yaml
  dart-api-examples/spoken-language-identification/pubspec.yaml
  dart-api-examples/streaming-asr/pubspec.yaml
  dart-api-examples/tts/pubspec.yaml
  dart-api-examples/vad-with-non-streaming-asr/pubspec.yaml
  dart-api-examples/vad/pubspec.yaml
  flutter-examples/streaming_asr/pubspec.yaml
  flutter-examples/tts/pubspec.yaml
  flutter/sherpa_onnx/pubspec.yaml
  flutter/sherpa_onnx_ios/ios/sherpa_onnx_ios.podspec
  flutter/sherpa_onnx_macos/macos/sherpa_onnx_macos.podspec
  harmony-os/SherpaOnnxHar/release.sh
  harmony-os/SherpaOnnxHar/sherpa_onnx/BuildProfile.ets
  harmony-os/SherpaOnnxHar/sherpa_onnx/README.md
  harmony-os/SherpaOnnxHar/sherpa_onnx/oh-package.json5
  harmony-os/SherpaOnnxSpeakerDiarization/entry/oh-package.json5
  harmony-os/SherpaOnnxSpeakerIdentification/entry/oh-package.json5
  harmony-os/SherpaOnnxStreamingAsr/entry/oh-package.json5
  harmony-os/SherpaOnnxTts/entry/oh-package.json5
  harmony-os/SherpaOnnxVadAsr/entry/README.md
  harmony-os/SherpaOnnxVadAsr/entry/oh-package.json5
  jitpack.yml
  mfc-examples/README.md
  new-release.sh
  nodejs-addon-examples/package.json
  nodejs-examples/package.json
  pom.xml
  scripts/wheel/sherpa-onnx-bin/setup.py
  scripts/wheel/sherpa-onnx-core/setup.py
  setup.py
  sherpa-onnx/csrc/version.cc
Labels: size:M

#2627 fix: hot update language for sencevoice
  sherpa-onnx/csrc/offline-recognizer-impl.h
  sherpa-onnx/csrc/offline-recognizer-sense-voice-impl.h
Labels: size:XS
